#!/usr/bin/bash

set -e

repo=runimage
for arch in any x86_64
    do
        if [ -d "$arch" ]
            then
                (cd "$arch"
                rm -f "$repo.db" "$repo.files"
                repo-add "$repo.db.tar.gz" *.tar.zst
                for repodb in $repo.db $repo.files
                    do
                        if [ -L "$repodb" ]
                            then
                                rm -fv "$repodb"
                                mv -v "$repodb.tar.gz" "$repodb"
                        fi
                done)
        fi
done

# git checkout --orphan latest_branch
# git add -A
# git commit -am "Update repo"
# git branch -D main
# git branch -m main
# git push -f origin main
# rm -rf .git/refs/original/
# git reflog expire --expire=now --all
# git gc --prune=now
# git gc --aggressive --prune=now
# git lfs prune
