#!/usr/bin/bash

set -e

repo=runimage
for arch in any x86_64
    do
        if [ -d "$arch" ]
            then
                unset NEWPKG
                (cd "$arch"
                rm -f "$repo.db" "$repo.files"
                repo-add "$repo.db.tar.gz" *.tar.zst
                for repodb in $repo.db $repo.files
                    do
                        if [ -L "$repodb" ]
                            then
                                rm -fv "$repodb"
                                mv -v "$repodb.tar.gz" "$repodb"
                        fi
                done)
                NEWPKG=($(find $arch -mmin -5 -type f -name "*.pkg.tar.*" -print))
                [ -n "$NEWPKG" ] && \
                gh release upload $arch "${NEWPKG[@]}" --clobber
        fi
done
